// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Minimal wire-compatible mirror of the kata-agent ttrpc API surface
// ateom-cloud-hypervisor needs after a CH snapshot restore: updating the
// restored guest's network interface and routes to the new pod's addresses.
//
// Field numbers and types mirror kata-containers 3.31.0
// src/libs/protocols/protos/{agent,types}.proto (Apache-2.0). The service is
// NOT declared here; calls go through ttrpc.Client.Call with the literal
// method names ("grpc.AgentService", "UpdateInterface"/"UpdateRoutes") so no
// ttrpc codegen plugin is required. kata's messages live in proto packages
// "grpc" and "types"; only field numbers matter on the wire, so they are
// flattened into this single package (type registration names differ, which
// is fine — names are never transmitted).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11-devel
// 	protoc        v4.25.3
// source: agent.proto

package agentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IPFamily int32

const (
	IPFamily_v4 IPFamily = 0
	IPFamily_v6 IPFamily = 1
)

// Enum value maps for IPFamily.
var (
	IPFamily_name = map[int32]string{
		0: "v4",
		1: "v6",
	}
	IPFamily_value = map[string]int32{
		"v4": 0,
		"v6": 1,
	}
)

func (x IPFamily) Enum() *IPFamily {
	p := new(IPFamily)
	*p = x
	return p
}

func (x IPFamily) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPFamily) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (IPFamily) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x IPFamily) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPFamily.Descriptor instead.
func (IPFamily) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type IPAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        IPFamily               `protobuf:"varint,1,opt,name=family,proto3,enum=ateomkataagent.IPFamily" json:"family,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Mask          string                 `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *IPAddress) GetFamily() IPFamily {
	if x != nil {
		return x.Family
	}
	return IPFamily_v4
}

func (x *IPAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *IPAddress) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

type Interface struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Device        string                 `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	IPAddresses   []*IPAddress           `protobuf:"bytes,3,rep,name=IPAddresses,proto3" json:"IPAddresses,omitempty"`
	Mtu           uint64                 `protobuf:"varint,4,opt,name=mtu,proto3" json:"mtu,omitempty"`
	HwAddr        string                 `protobuf:"bytes,5,opt,name=hwAddr,proto3" json:"hwAddr,omitempty"`
	DevicePath    string                 `protobuf:"bytes,6,opt,name=devicePath,proto3" json:"devicePath,omitempty"`
	Type          string                 `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	RawFlags      uint32                 `protobuf:"varint,8,opt,name=raw_flags,json=rawFlags,proto3" json:"raw_flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interface) Reset() {
	*x = Interface{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interface) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interface) ProtoMessage() {}

func (x *Interface) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interface.ProtoReflect.Descriptor instead.
func (*Interface) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Interface) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Interface) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Interface) GetIPAddresses() []*IPAddress {
	if x != nil {
		return x.IPAddresses
	}
	return nil
}

func (x *Interface) GetMtu() uint64 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

func (x *Interface) GetHwAddr() string {
	if x != nil {
		return x.HwAddr
	}
	return ""
}

func (x *Interface) GetDevicePath() string {
	if x != nil {
		return x.DevicePath
	}
	return ""
}

func (x *Interface) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Interface) GetRawFlags() uint32 {
	if x != nil {
		return x.RawFlags
	}
	return 0
}

type Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dest          string                 `protobuf:"bytes,1,opt,name=dest,proto3" json:"dest,omitempty"`
	Gateway       string                 `protobuf:"bytes,2,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Device        string                 `protobuf:"bytes,3,opt,name=device,proto3" json:"device,omitempty"`
	Source        string                 `protobuf:"bytes,4,opt,name=source,proto3" json:"source,omitempty"`
	Scope         uint32                 `protobuf:"varint,5,opt,name=scope,proto3" json:"scope,omitempty"`
	Family        IPFamily               `protobuf:"varint,6,opt,name=family,proto3,enum=ateomkataagent.IPFamily" json:"family,omitempty"`
	Flags         uint32                 `protobuf:"varint,7,opt,name=flags,proto3" json:"flags,omitempty"`
	Mtu           uint32                 `protobuf:"varint,8,opt,name=mtu,proto3" json:"mtu,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Route) Reset() {
	*x = Route{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Route) ProtoMessage() {}

func (x *Route) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Route.ProtoReflect.Descriptor instead.
func (*Route) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Route) GetDest() string {
	if x != nil {
		return x.Dest
	}
	return ""
}

func (x *Route) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Route) GetDevice() string {
	if x != nil {
		return x.Device
	}
	return ""
}

func (x *Route) GetSource() string {
	if x != nil {
		return x.Source
	}
	return ""
}

func (x *Route) GetScope() uint32 {
	if x != nil {
		return x.Scope
	}
	return 0
}

func (x *Route) GetFamily() IPFamily {
	if x != nil {
		return x.Family
	}
	return IPFamily_v4
}

func (x *Route) GetFlags() uint32 {
	if x != nil {
		return x.Flags
	}
	return 0
}

func (x *Route) GetMtu() uint32 {
	if x != nil {
		return x.Mtu
	}
	return 0
}

type Routes struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        []*Route               `protobuf:"bytes,1,rep,name=Routes,proto3" json:"Routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Routes) Reset() {
	*x = Routes{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Routes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Routes) ProtoMessage() {}

func (x *Routes) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Routes.ProtoReflect.Descriptor instead.
func (*Routes) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *Routes) GetRoutes() []*Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type UpdateInterfaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Interface     *Interface             `protobuf:"bytes,1,opt,name=interface,proto3" json:"interface,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateInterfaceRequest) Reset() {
	*x = UpdateInterfaceRequest{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateInterfaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateInterfaceRequest) ProtoMessage() {}

func (x *UpdateInterfaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateInterfaceRequest.ProtoReflect.Descriptor instead.
func (*UpdateInterfaceRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateInterfaceRequest) GetInterface() *Interface {
	if x != nil {
		return x.Interface
	}
	return nil
}

type UpdateRoutesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Routes        *Routes                `protobuf:"bytes,1,opt,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoutesRequest) Reset() {
	*x = UpdateRoutesRequest{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoutesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoutesRequest) ProtoMessage() {}

func (x *UpdateRoutesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoutesRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoutesRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateRoutesRequest) GetRoutes() *Routes {
	if x != nil {
		return x.Routes
	}
	return nil
}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\x0eateomkataagent\"k\n" +
	"\tIPAddress\x120\n" +
	"\x06family\x18\x01 \x01(\x0e2\x18.ateomkataagent.IPFamilyR\x06family\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x12\n" +
	"\x04mask\x18\x03 \x01(\tR\x04mask\"\xef\x01\n" +
	"\tInterface\x12\x16\n" +
	"\x06device\x18\x01 \x01(\tR\x06device\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12;\n" +
	"\vIPAddresses\x18\x03 \x03(\v2\x19.ateomkataagent.IPAddressR\vIPAddresses\x12\x10\n" +
	"\x03mtu\x18\x04 \x01(\x04R\x03mtu\x12\x16\n" +
	"\x06hwAddr\x18\x05 \x01(\tR\x06hwAddr\x12\x1e\n" +
	"\n" +
	"devicePath\x18\x06 \x01(\tR\n" +
	"devicePath\x12\x12\n" +
	"\x04type\x18\a \x01(\tR\x04type\x12\x1b\n" +
	"\traw_flags\x18\b \x01(\rR\brawFlags\"\xd5\x01\n" +
	"\x05Route\x12\x12\n" +
	"\x04dest\x18\x01 \x01(\tR\x04dest\x12\x18\n" +
	"\agateway\x18\x02 \x01(\tR\agateway\x12\x16\n" +
	"\x06device\x18\x03 \x01(\tR\x06device\x12\x16\n" +
	"\x06source\x18\x04 \x01(\tR\x06source\x12\x14\n" +
	"\x05scope\x18\x05 \x01(\rR\x05scope\x120\n" +
	"\x06family\x18\x06 \x01(\x0e2\x18.ateomkataagent.IPFamilyR\x06family\x12\x14\n" +
	"\x05flags\x18\a \x01(\rR\x05flags\x12\x10\n" +
	"\x03mtu\x18\b \x01(\rR\x03mtu\"7\n" +
	"\x06Routes\x12-\n" +
	"\x06Routes\x18\x01 \x03(\v2\x15.ateomkataagent.RouteR\x06Routes\"Q\n" +
	"\x16UpdateInterfaceRequest\x127\n" +
	"\tinterface\x18\x01 \x01(\v2\x19.ateomkataagent.InterfaceR\tinterface\"E\n" +
	"\x13UpdateRoutesRequest\x12.\n" +
	"\x06routes\x18\x01 \x01(\v2\x16.ateomkataagent.RoutesR\x06routes*\x1a\n" +
	"\bIPFamily\x12\x06\n" +
	"\x02v4\x10\x00\x12\x06\n" +
	"\x02v6\x10\x01BWZUgithub.com/agent-substrate/substrate/cmd/ateom-cloud-hypervisor/internal/kata/agentpbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_agent_proto_goTypes = []any{
	(IPFamily)(0),                  // 0: ateomkataagent.IPFamily
	(*IPAddress)(nil),              // 1: ateomkataagent.IPAddress
	(*Interface)(nil),              // 2: ateomkataagent.Interface
	(*Route)(nil),                  // 3: ateomkataagent.Route
	(*Routes)(nil),                 // 4: ateomkataagent.Routes
	(*UpdateInterfaceRequest)(nil), // 5: ateomkataagent.UpdateInterfaceRequest
	(*UpdateRoutesRequest)(nil),    // 6: ateomkataagent.UpdateRoutesRequest
}
var file_agent_proto_depIdxs = []int32{
	0, // 0: ateomkataagent.IPAddress.family:type_name -> ateomkataagent.IPFamily
	1, // 1: ateomkataagent.Interface.IPAddresses:type_name -> ateomkataagent.IPAddress
	0, // 2: ateomkataagent.Route.family:type_name -> ateomkataagent.IPFamily
	3, // 3: ateomkataagent.Routes.Routes:type_name -> ateomkataagent.Route
	2, // 4: ateomkataagent.UpdateInterfaceRequest.interface:type_name -> ateomkataagent.Interface
	4, // 5: ateomkataagent.UpdateRoutesRequest.routes:type_name -> ateomkataagent.Routes
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
